### ISSUE TITLE
Implementing a remote authentication.

### ISSUE THREAD

**Issue by NachoDonaire** [Daniexp/ft_transcendence#2]
## Implement a remote authentication

**Description**
In this major module, the goal is to implement the following authentication system:
OAuth 2.0 authentication with 42 . Key features and objectives include:

  ◦ Integrate the authentication system, allowing users to securely sign in.
  ◦ Obtain the necessary credentials and permissions from the authority to enable a secure login.
  ◦ Implement user-friendly login and authorization flows that adhere to best practices and security standards.
  ◦ Ensure the secure exchange of authentication tokens and user information between the web application and the authentication provider.

**User Story**
As a user I want to be able to login in a secure way in the web  using my 42 intra credentials.

**Acceptance Criteria**
- [ ] Pass the properly tests
- [ ] Friendly and functional interface

**Subtasks**
- [ ] Research and understood about OAuth2 protocol
- [ ] Implement a valid and secure way to get access to 42 API
- [ ] Insert in a properly way the necessary credentials into our database
- [ ] Discuss about the implementation of repeated emails. Also, apply the final agreement
- [ ] Implement the view of the log in url

**Related Issues**
- Issue #123
- Issue #456

**Dependencies**
- Depends
 Active database
- Blocks
 None

**Priority**
- Medium

**Assignees**
- @NachoDonaire 

**Estimated Time**
- 5 hours / 14 days

Member | Refinement Agree |
---- | --- |
Jsanfeli |  |
Ndonaire | Yes |
Dexposit|  |

**Comment by Daniexp** [comment]
closing issue, because was created as a issue before ending the task writing.
