### ISSUE TITLE
Start Game

### ISSUE THREAD

**Issue by KiriamBlu** [Daniexp/ft_transcendence#3]
##  Start game

**Description**
Start defining game interactions and processing. This task will be terminated once all basic interactions are defined and tested

**User Story**
I want to start interacting with all parts involved in creatiing a game with all needs defined by subject (mayors and minors included)

**Acceptance Criteria**
- [x] @NachoDonaire reviewed the game, and approved implementation
- [x] @DaniExp reviewed the game, and approved implementation
- [x] @KiriamBlu reviewed code and tested

**Subtasks**
- [x] Backend connection
- [x] Define the game structure (processing in backend and connections defined)
- [x] Frontend socket connection
- [x] Live and fluent connection and processing

**Priority**
- High

**Estimated Time**
- 3 days / 14 days

**Additional Context**

Member | Refinement Agree |
---- | --- |
Jsanfeli | Yes |
Ndonaire | Yes |
Dexposit| Yes |

**Comment by Daniexp** [comment]
@KiriamBlu - Reviewed the game (basic structure) and approved.
